spring:
  main:
    banner-mode: console
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    schema: schema-postgre.sql